[phases.setup]
nixPkgs = ["python311", "zbar", "libzbar", "gcc", "libpng", "zlib", "opencv", "cmake", "glibc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bot.py"
